### ISSUE TITLE
Add `padding` property to ChatBubble widget

### ISSUE THREAD

**Issue by davidmednikov** [KinjalDhamat312/FlutterChatBubble#1]
It would be a nice addition to be able to set our own custom padding. I see that the `ChatBubble` widget has a `setPadding()` function that determines the padding size based on the clipper and bubble type, but think that it would be useful to be able to define the padding myself as well.

Thank you for this excellent plugin!

**Comment by abdulrehmank7** [comment]
Checkout custom chat bubble widget class. https://arkapp.medium.com/chat-bubble-widget-for-flutter-95d3bb82ddd8

**Comment by KinjalDhamat312** [comment]
In flutter_chat_bubble 2.0.0 version, padding property is added.
