### ISSUE TITLE
A problem occurred evaluating project ':flutter_chat_bubble'.

### ISSUE THREAD

**Issue by kenaitian** [KinjalDhamat312/FlutterChatBubble#9]
Launching lib/main.dart on LM Q610 FGN in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ken/.pub-cache/hosted/pub.dartlang.org/flutter_chat_bubble-2.0.0/android/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':flutter_chat_bubble'.
> Could not get unknown property 'flutter' for DefaultConfig$AgpDecorated_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=SigningConfig$AgpDecorated_Decorated{name=debug, storeFile=/Users/ken/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null}, resConfig=[], buildConfigFields={}, resValues={}, proguardFiles=[], consumerProguardFiles=[], manifestPlaceholders={}, wearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig$AgpDecorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by zakblacki** [comment]
workaround either downgrade kotlin version or upgraded it from the package itself build gradle

**Comment by KinjalDhamat312** [comment]
Check latest version 2.0.2
